// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: HMI_OUTPUT_1

// #include "ui.h"

// void button1_on(lv_event_t * e)
// {
// 	// Your code here
// }

// void button1_off(lv_event_t * e)
// {
// 	// Your code here
// }

// void button2_on(lv_event_t * e)
// {
// 	// Your code here
// }

// void button2_off(lv_event_t * e)
// {
// 	// Your code here
// }

// void button3_on(lv_event_t * e)
// {
// 	// Your code here
// }

// void button3_off(lv_event_t * e)
// {
// 	// Your code here
// }

// void button4_on(lv_event_t * e)
// {
// 	// Your code here
// }

// void button4_off(lv_event_t * e)
// {
// 	// Your code here
// }
