// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: HMI_OUTPUT_1

#ifndef _HMI_OUTPUT_1_UI_H
#define _HMI_OUTPUT_1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label1;
void ui_event_OUTPUT1_ON(lv_event_t * e);
extern lv_obj_t * ui_OUTPUT1_ON;
extern lv_obj_t * ui_out1on;
void ui_event_OUTPUT1_OFF(lv_event_t * e);
extern lv_obj_t * ui_OUTPUT1_OFF;
extern lv_obj_t * ui_out1off;
extern lv_obj_t * ui_Label2;
void ui_event_OUTPUT2_ON(lv_event_t * e);
extern lv_obj_t * ui_OUTPUT2_ON;
extern lv_obj_t * ui_out2on;
void ui_event_OUTPUT2_OFF(lv_event_t * e);
extern lv_obj_t * ui_OUTPUT2_OFF;
extern lv_obj_t * ui_out2off;
extern lv_obj_t * ui_Label3;
void ui_event_OUTPUT3_ON(lv_event_t * e);
extern lv_obj_t * ui_OUTPUT3_ON;
extern lv_obj_t * ui_out3on;
void ui_event_OUTPUT3_OFF(lv_event_t * e);
extern lv_obj_t * ui_OUTPUT3_OFF;
extern lv_obj_t * ui_out3off;
extern lv_obj_t * ui_Label4;
void ui_event_OUTPUT4_ON(lv_event_t * e);
extern lv_obj_t * ui_OUTPUT4_ON;
extern lv_obj_t * ui_out4on;
void ui_event_OUTPUT4_OFF(lv_event_t * e);
extern lv_obj_t * ui_OUTPUT4_OFF;
extern lv_obj_t * ui_out4off;
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_ARIAL20);
LV_FONT_DECLARE(ui_font_arial16);
LV_FONT_DECLARE(ui_font_arial16_bpp8);
LV_FONT_DECLARE(ui_font_arial10);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
