// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: HMI_OUTPUT_1

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void button1_on(lv_event_t * e);
void button1_off(lv_event_t * e);
void button2_on(lv_event_t * e);
void button2_off(lv_event_t * e);
void button3_on(lv_event_t * e);
void button3_off(lv_event_t * e);
void button4_on(lv_event_t * e);
void button4_off(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
